import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import JSZip from "jszip";
import { readFile } from "fs/promises";
import { join } from "path";
import { cwd } from "process";

// Helper type for Block
type BlockWithFile = {
  id: string;
  type: string;
  content: string;
  properties: string | null;
  order: number;
  file?: {
    url: string;
    name: string;
  } | null;
};

// Simple Markdown to LaTeX converter
function convertMarkdownToLatex(text: string): string {
  if (!text) return "";

  let latex = text;

  // Escape special LaTeX characters (excluding those used in math delimiters if possible, 
  // but for a simple regex approach, we must be careful not to break math)
  // Strategy: Split by math delimiters ($...$ or $$...$$), escape text parts, leave math parts alone.
  
  const parts = latex.split(/(\$\$[\s\S]*?\$\$|\$[\s\S]*?\$)/g);
  
  latex = parts.map((part) => {
    if (part.startsWith("$")) {
      return part; // Return math as is
    }
    
    // Escape special characters in text
    let escaped = part
      .replace(/\\/g, '\\textbackslash{}')
      .replace(/([&%$#_{}])/g, '\\$1')
      .replace(/~/g, '\\textasciitilde{}')
      .replace(/\^/g, '\\textasciicircum{}');

    // Convert Markdown formatting
    // Headers
    escaped = escaped.replace(/^### (.*$)/gm, '\\subsubsection*{$1}');
    escaped = escaped.replace(/^## (.*$)/gm, '\\subsection*{$1}');
    escaped = escaped.replace(/^# (.*$)/gm, '\\section*{$1}');

    // Bold
    escaped = escaped.replace(/\*\*(.*?)\*\*/g, '\\textbf{$1}');
    
    // Italic
    escaped = escaped.replace(/\*(.*?)\*/g, '\\textit{$1}');

    // Lists (Simple conversion)
    // Identify blocks of lists - this is hard with simple regex on single pass.
    // We'll just do simple bullet points replacement for now.
    escaped = escaped.replace(/^\s*-\s+(.*$)/gm, '\\begin{itemize}\n\\item $1\n\\end{itemize}');
    // Fix nested itemize which is ugly with this replace:
    // A better approach for lists would be needed for perfect rendering, 
    // but this is a "good enough" start.
    // Clean up immediate close/open of itemize
    escaped = escaped.replace(/\\end{itemize}\s*\\begin{itemize}/g, '');

    return escaped;
  }).join("");

  return latex;
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const resolvedParams = await params;
  const projectId = resolvedParams.id;

  try {
    // 1. Fetch Project Data
    const project = await db.project.findUnique({
      where: { id: projectId },
      include: {
        summaries: {
          orderBy: { createdAt: 'asc' }, // Or property index if available, usually created order is fine or we need an updated order field
          include: {
            blocks: {
              orderBy: { order: 'asc' },
              include: {
                file: true
              }
            }
          }
        }
      }
    });

    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    const zip = new JSZip();
    const assetsFolder = zip.folder("assets");
    const chaptersFolder = zip.folder("chapters");

    // 2. Create main.tex
    let mainTex = `\\documentclass[12pt,a4paper]{report}
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{graphicx}
\\usepackage{amsmath}
\\usepackage{amssymb}
\\usepackage{hyperref}
\\usepackage{parskip}
\\usepackage{geometry}
\\geometry{a4paper, margin=2.5cm}

\\title{${project.name}}
\\author{Generated by ScriptBot}
\\date{\\today}

\\begin{document}

\\maketitle
\\tableofcontents

`;

    // 3. Process Summaries
    for (const summary of project.summaries) {
      const safeTitle = summary.title.replace(/[^a-zA-Z0-9-]/g, '_');
      const chapterFileName = `chapter_${summary.id}.tex`;
      
      mainTex += `\\include{chapters/${chapterFileName.replace('.tex', '')}}\n`;

      let chapterContent = `\\chapter{${summary.title}}\n\n`;

      for (const block of summary.blocks) {
        if (block.type === 'TEXT') {
          chapterContent += convertMarkdownToLatex(block.content) + "\n\n";
        } else if (block.type === 'LATEX') {
           // Assume block content is raw latex (e.g. math environment)
           // Check if it's wrapped in delimiters, if not, wrapping might be unsafe if it's a big block.
           // Usually it's safer to just dump it. 
           // If it's pure math, it likely needs $$ or equation env. 
           // Let's assume the user put delimiters or we wrap it in specific env if needed.
           // Based on usual behavior, let's just append it.
           // If it lacks delimiters but is math, we might want to check.
           // For now: Raw output.
           chapterContent += block.content + "\n\n";
        } else if (block.type === 'IMAGE' || block.type === 'PENDING_IMAGE') {
           if (block.file && block.file.url) {
             const fileName = block.file.url.split('/').pop();
             if (fileName) {
               // Physical path
               const filePath = join(cwd(), "public", "uploads", projectId, fileName);
               
               try {
                 const fileBuffer = await readFile(filePath);
                 assetsFolder?.file(fileName, fileBuffer);
                 
                 chapterContent += `\\begin{figure}[h]
  \\centering
  \\includegraphics[width=0.8\\textwidth]{assets/${fileName}}
  \\caption{Image}
\\end{figure}\n\n`;
               } catch (e) {
                 console.error(`Failed to read image file: ${filePath}`, e);
                 chapterContent += `% Error: Could not include image ${fileName}\n\n`;
               }
             }
           }
        }
      }

      chaptersFolder?.file(chapterFileName, chapterContent);
    }

    mainTex += `\\end{document}`;
    zip.file("main.tex", mainTex);

    // 4. Generate ZIP
    const zipContent = await zip.generateAsync({ type: "blob" });
    const arrayBuffer = await zipContent.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    // 5. Return Response
    return new NextResponse(buffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${project.name.replace(/[^a-zA-Z0-9-]/g, '_')}_latex.zip"`,
      },
    });

  } catch (error) {
    console.error("Export error:", error);
    return NextResponse.json({ error: "Failed to export project" }, { status: 500 });
  }
}
