"use client"

import { useState } from "react"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Loader2, Upload, Check, X } from "lucide-react"
import { uploadImage } from "@/app/actions/upload" // We need to create this
import { updateSummaryBlock } from "@/app/actions/blocks"

interface PendingBlock {
  id: string
  content: string // Description
}

interface BatchUploadDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  pendingBlocks: PendingBlock[]
  onComplete: () => void
}

export function BatchUploadDialog({ open, onOpenChange, pendingBlocks, onComplete }: BatchUploadDialogProps) {
  const [files, setFiles] = useState<Record<string, File>>({})
  const [uploading, setUploading] = useState(false)
  const [progress, setProgress] = useState(0)

  const handleFileChange = (blockId: string, file: File | null) => {
    if (file) {
      setFiles(prev => ({ ...prev, [blockId]: file }))
    } else {
      setFiles(prev => {
        const newFiles = { ...prev }
        delete newFiles[blockId]
        return newFiles
      })
    }
  }

  const handleUpload = async () => {
    setUploading(true)
    let completed = 0
    const total = Object.keys(files).length

    for (const [blockId, file] of Object.entries(files)) {
      try {
        const formData = new FormData()
        formData.append("file", file)
        
        // Upload image
        const uploadResult = await uploadImage(formData)
        if (uploadResult.success && uploadResult.url) {
            // Update block to be an image block
            await updateSummaryBlock(blockId, uploadResult.url, "image")
        }
      } catch (error) {
        console.error("Failed to upload image for block", blockId, error)
      }
      completed++
      setProgress((completed / total) * 100)
    }

    setUploading(false)
    onOpenChange(false)
    onComplete() // Trigger refresh or state update in parent
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[600px] max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Upload Requested Images</DialogTitle>
          <DialogDescription>
            Please upload images for the following requests generated by the AI.
          </DialogDescription>
        </DialogHeader>

        <div className="grid gap-6 py-4">
          {pendingBlocks.map((block, index) => {
            let description = block.content;
            let page: number | undefined;
            let fileUrl: string | undefined;
            try {
                const data = JSON.parse(block.content);
                if (typeof data === 'object' && data !== null) {
                    description = data.description || block.content;
                    page = data.page;
                    fileUrl = data.fileUrl;
                }
            } catch (e) {}

            return (
            <div key={block.id} className="grid gap-2 border p-4 rounded-lg bg-muted/20">
              <div className="flex items-start gap-2">
                <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-medium text-primary">
                  {index + 1}
                </span>
                <div className="grid gap-1.5 flex-1">
                  <div className="flex items-center gap-2">
                    <Label className="text-base font-medium leading-none">
                        {description}
                    </Label>
                    {page && (
                        fileUrl ? (
                            <a href={`${fileUrl}#page=${page}`} target="_blank" rel="noopener noreferrer">
                                <span className="inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-semibold text-muted-foreground bg-background hover:bg-accent hover:text-accent-foreground cursor-pointer transition-colors">
                                    Page {page}
                                </span>
                            </a>
                        ) : (
                            <span className="inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-semibold text-muted-foreground bg-background">
                                Page {page}
                            </span>
                        )
                    )}
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Upload an image for this section.
                  </p>
                </div>
              </div>
              
              <div className="flex items-center gap-2 mt-2">
                <Input
                  type="file"
                  accept="image/*"
                  onChange={(e) => handleFileChange(block.id, e.target.files?.[0] || null)}
                  className="flex-1"
                />
                {files[block.id] ? (
                    <Check className="h-4 w-4 text-green-500" />
                ) : (
                    <div className="w-4" />
                )}
              </div>
            </div>
            );
          })}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={uploading}>
            Cancel
          </Button>
          <Button onClick={handleUpload} disabled={uploading || Object.keys(files).length === 0} className="gap-2">
            {uploading ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Uploading ({Math.round(progress)}%)
              </>
            ) : (
              <>
                <Upload className="h-4 w-4" />
                Upload Selected ({Object.keys(files).length})
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
