'use client';

import { useState, useTransition, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Sparkles, Loader2, FileText, CheckCircle2 } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { generateSummaryFromFiles } from "@/app/actions/ai";
import { getFiles } from "@/app/actions/files";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Progress } from "@/components/ui/progress";

import { cn } from "@/lib/utils";

interface GenerateSummaryButtonProps {
  projectId: string;
  onSuccess?: () => void;
}

export function GenerateSummaryButton({ projectId, onSuccess }: GenerateSummaryButtonProps) {
  const [open, setOpen] = useState(false);
  const [selectedFileId, setSelectedFileId] = useState<string>("all");
  const [files, setFiles] = useState<{ id: string; name: string }[]>([]);
  const [loadingFiles, setLoadingFiles] = useState(false);
  const [imageSource, setImageSource] = useState<'google' | 'manual' | 'none'>('google');
  
  const [isPending, startTransition] = useTransition();
  const [progress, setProgress] = useState(0);
  const [statusText, setStatusText] = useState("");

  useEffect(() => {
    if (open) {
      setLoadingFiles(true);
      getFiles(projectId).then((result) => {
        if (result.files) {
          setFiles(result.files);
        }
        setLoadingFiles(false);
      });
    }
  }, [open, projectId]);

  // Simulated progress effect
  useEffect(() => {
    if (isPending) {
      setProgress(0);
      setStatusText("Initializing...");
      
      const interval = setInterval(() => {
        setProgress((prev) => {
          if (prev >= 90) return prev; // Hold at 90% until done
          
          // Dynamic speed: fast at first, then slower
          const increment = prev < 30 ? 5 : prev < 60 ? 2 : 0.5;
          return prev + increment;
        });
      }, 200);

      // Status text updates
      const timeouts = [
        setTimeout(() => setStatusText("Reading file content..."), 1000),
        setTimeout(() => setStatusText("Analyzing structure..."), 3000),
        setTimeout(() => setStatusText("Generating summary blocks..."), 6000),
        setTimeout(() => setStatusText("Formatting formulas..."), 9000),
      ];

      return () => {
        clearInterval(interval);
        timeouts.forEach(clearTimeout);
      };
    } else {
      setProgress(0);
      setStatusText("");
    }
  }, [isPending]);

  const handleGenerate = () => {
    startTransition(async () => {
      const fileIdToUse = selectedFileId === "all" ? undefined : selectedFileId;
      // Pass empty string for title as it will be generated by AI
      const result = await generateSummaryFromFiles(projectId, "", fileIdToUse, imageSource);
      
      if (result.success && result.summaryId) {
        setProgress(100);
        setStatusText("Done!");
        setTimeout(() => {
          setOpen(false);
          onSuccess?.();
        }, 500);
      } else {
        alert(result.error || "Failed to generate summary");
      }
    });
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className="gap-2 border-primary/20 hover:bg-primary/5 hover:text-primary">
          <Sparkles className="h-4 w-4" />
          Generate with AI
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Generate Summary with AI</DialogTitle>
          <DialogDescription>
            Create a structured summary from your project files.
          </DialogDescription>
        </DialogHeader>
        
        <div className="grid gap-6 py-4">

          <div className="grid gap-2">
            <Label>Source File</Label>
            <Select 
              value={selectedFileId} 
              onValueChange={setSelectedFileId}
              disabled={isPending || loadingFiles}
            >
              <SelectTrigger>
                <SelectValue placeholder={loadingFiles ? "Loading files..." : "Select a file"} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">
                  <span className="font-medium">All Files</span>
                  <span className="text-muted-foreground ml-2 text-xs">({files.length} files)</span>
                </SelectItem>
                {files.map((file) => (
                  <SelectItem key={file.id} value={file.id}>
                    <div className="flex items-center gap-2 truncate max-w-[280px]">
                      <FileText className="h-3 w-3 text-muted-foreground shrink-0" />
                      <span className="truncate">{file.name}</span>
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <p className="text-[0.8rem] text-muted-foreground">
              Choose "All Files" to combine everything, or select a specific file for a focused summary.
            </p>
          </div>

          <div className="grid gap-2">
            <Label>Image Handling</Label>
            <Select 
              value={imageSource} 
              onValueChange={(val: any) => setImageSource(val)}
              disabled={isPending}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="google">
                  <span className="font-medium">Google Search</span>
                  <span className="text-muted-foreground ml-2 text-xs">(Auto-fetch)</span>
                </SelectItem>
                <SelectItem value="manual">
                  <span className="font-medium">Manual Upload</span>
                  <span className="text-muted-foreground ml-2 text-xs">(Upload later)</span>
                </SelectItem>
                <SelectItem value="none">
                  <span className="font-medium">No Images</span>
                  <span className="text-muted-foreground ml-2 text-xs">(Text only)</span>
                </SelectItem>
              </SelectContent>
            </Select>
            <p className="text-[0.8rem] text-muted-foreground">
              {imageSource === 'google' && "Automatically search and insert relevant images from Google."}
              {imageSource === 'manual' && "AI will suggest images, and you can upload them in a batch dialog."}
              {imageSource === 'none' && "Generate text only, with placeholders for images."}
            </p>
          </div>

          {isPending && (
            <div className="space-y-2 animate-in fade-in slide-in-from-top-2 duration-300">
              <div className="flex justify-between text-xs text-muted-foreground">
                <span>{statusText}</span>
                <span>{Math.round(progress)}%</span>
              </div>
              <Progress value={progress} className="h-2" />
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => setOpen(false)} disabled={isPending}>
            Cancel
          </Button>
          <Button onClick={handleGenerate} disabled={isPending} className="gap-2 min-w-[120px]">
            {isPending ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Generating
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4" />
                Generate
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
